

country = { 
    tag = AFG
    alignment = { x = 0 y = 0 }

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	manpower = 330
	capital = 	1437

    ownedprovinces =      {
1437 1421 1420 1419 1408 
	 }
    controlledprovinces = {
1437 1421 1420 1419 1408  
	  }
    nationalprovinces =   {
1437 1421 1420 1419 1408 
	  }


#####################
###AFGHANISTAN OOB###
#####################

landunit = {
 id = { type = 28007 id = 1 }
 location = 1437
 name = "Central Army"

  division = {
   id = { type = 28007 id = 2 }
   name = "Royal Afghan Household"
   strength = 80
   type = infantry
             }

  division = {
   id = { type = 28007 id = 3 }
   name = "1st Infantry Division"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 4 }
   name = "2nd Infantry Division"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 5 }
   name = "4th Infantry Division"
   strength = 30
   type = militia
             }

           }

##########################
##########################
 
landunit = {
 id = { type = 28007 id = 6 }
 location = 1408
 name = "Southern Army"

  division = {
   id = { type = 28007 id = 7 }
   name = "5th Infantry Division"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 8 }
   name = "6th Infantry Division"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 9 }
   name = "7th Infantry Division"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 10 }
   name = "Farah Cavalry"
   strength = 30
   type = cavalry

           }

###########################
############################

landunit = {
 id = { type = 28007 id = 11 }
 location = 1419 #Various Mixed Divisions, each based at different city humped in one landunit#
 name = "Mixed Army"
 
  division = {
   id = { type = 28007 id = 12 }
   name = "1st Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 13 }
   name = "2nd Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 14 }
   name = "3rd Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 15 }
   name = "4th Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 16 }
   name = "5th Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 17 }
   name = "6th Mixed Infantry"
   strength = 30
   type = militia
             }

  division = {
   id = { type = 28007 id = 18 }
   name = "7th Mixed Infantry"
   strength = 30
   type = militia
             }

         }

#########################
#########################
} 
