
  country = { 
    tag = AST
	alignment = { x = 100 y = 0 }
	
	manpower = 390
	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 2076

	techlevels = { 
		12000 13000 11000 14000 1000 1100 2000 5000 6000 9000 10000 8000
		8100 3000 3100 4000 4100 4200 4300
	 }
	 techapps = {
		12001 11001 11004 14001 14014 1001 6003 6004 3002 3005 4001 4101
		4102 4201 4202  4203  4204 3101 14005 1107
		4301 4302 4303
	}


    ownedprovinces =      {
	2074 2073 2075 2076 2077 2081 2078 2080 2079 2065 2106 2107 2105 2109 2108 2112 2110 2101 2097 2111 2113 2093 2117 2066 2067 2068 2092 2094 2096 2095 2060 2063 2062 2058 2064 2055 2041 2057 2044 2043 2042 
	2072 2020 2024 1988 1989 1990 1991 2025 1966 1928 2023 2003 

	 }
    controlledprovinces = {
	2074 2073 2075 2076 2077 2081 2078 2080 2079 2065 2106 2107 2105 2109 2108 2112 2110 2101 2097 2111 2113 2093 2117 2066 2067 2068 2092 2094 2096 2095 2060 2063 2062 2058 2064 2055 2041 2057 2044 2043 2042 
	2072 2020 2024 1988 1989 1990 1991 2025 1966 1928 2023 2003 

	  }
    nationalprovinces =   {
	2074 2073 2075 2076 2077 2081 2078 2080 2079 2065 2106 2107 2105 2109 2108 2112 2110 2101 2097 2111 2113 2093 2117 2066 2067 2068 2092 2094 2096 2095 2060 2063 2062 2058 2064 2055 2041 2057 2044 2043 2042 
	2072 2020 2024 1988 1989 1990 1991 2025 1966 1928 2023 2003 

	  }
####################
###AUSTRALIAN OOB###
####################

landunit = {
 id = { type = 28002 id = 1 }
 name = "2nd Imperial Force"
 location = 2078

  division = {
   id = { type = 28002 id = 2 }
   name = "6th Australian Division"
   strength = 100
   type = infantry
             }

  division = {
   id = { type = 28002 id = 3 }
   name = "7th Australian Division"
   strength = 100
   type = infantry
             }

  division = {
   id = { type = 28002 id = 4 }
   name = "9th Australian Division"
   strength = 100
   type = infantry
             }

  division = {
   id = { type = 28002 id = 5 }
   name = "8th Australian Division"
   strength = 100
   type = infantry
   extra = artillery
             }

  division = {
   id = { type = 28002 id = 6 }
   name = "23rd Australian Division"
   strength = 30
   type = infantry
   extra = engineer
             }

  division = {
   id = { type = 28002 id = 7 }
   name = "1st Armoured Division"
   strength = 100
   type = panzer
   model = 1
             }
         }

##########################
##########################

landunit = {
 id = { type = 28002 id = 8 }
 name = "Northern Command"
 location = 2105

  division = {
   id = { type = 28002 id = 9 }
   name = "1st Motorized Brigade"
   strength = 30
   type = motorized
             }

  division = {
   id = { type = 28002 id = 10 }
   name = "7th Infantry Brigade"
   strength = 30
   type = infantry
             }

  division = {
   id = { type = 28002 id = 11 }
   name = "11th Infantry Brigade"
   strength = 30
   type = infantry
             }

  division = {
   id = { type = 28002 id = 12 }
   name = "29th Infantry Brigade"
   strength = 30
   type = infantry 
             }
           }

#################################
#################################

landunit = {
 id = { type = 28002 id = 14 }
 name = "Eastern Command"
 location = 2078

  division = {
   id = { type = 28002 id = 15 }
   name = "1st Cavalry Division"
   strength = 100
   type = cavalry
             }

  division = {
   id = { type = 28002 id = 16 }
   name = "1st Infantry Division"
   strength = 100
   type = infantry
   extra = engineer
             }

  division = {
   id = { type = 28002 id = 17 }
   name = "2nd Infantry Division"
   strength = 100
   type = infantry
   extra = artillery
             }
          }

################################
################################

landunit = {
 id = { type = 28002 id = 18 }
 name = "Southern Command"
 location = 2075

  division = { 
   id = { type = 28002 id = 19 }
   name = "2nd Cavalry Division"
   strength = 100
   type = cavalry
             }

  division = {
   id = { type = 28002 id = 20 }
   name = "3rd Infantry Division"
   strength = 100
   type = infantry
   extra = artillery
             }

  division = {
   id = { type = 28002 id = 21 }  
   name = "4th Infantry Division"
   strength = 100
   type = infantry
   extra = artillery
              }

  division = {
   id = { type = 28002 id = 22 }
   name = "6th Cavalry Brigade"
   strength = 30
   type = cavalry
             }

  division = {
   id = { type = 28002 id = 23 }
   name = "3rd Infantry Brigade"
   strength = 30
   type = infantry
             }
  
  division = {
   id = { type = 28002 id = 24 }
   name = "12th Infantry Brigade"
   strength = 30
   type = infantry
             }
         }

#############################
#############################

landunit = {
 id = { type = 28002 id = 25 }
 name = "Western Command"
 location = 2042

  division = {
   id = { type = 28002 id = 26 }
   name = "13th Infantry Brigade"
   strength = 30
   type = infantry
             }
          }

##############################
##############################
navalunit = {
		id = { type = 28002 id = 27 }
		location = 2075
		name = "1st Transport"

		division = { 
			id = { type = 28002 id = 28 } 
			name = "1st Transport" 
			type = transport 
			}
		}
##############################
##############################
# Supplies to Port Moresby
	convoy = { 
		id = { type = 28002 id = 29 } 
		transports = 10
		escorts = 0
		rubber = no 
		coal = no 
		steel = no 
		oil = no
		supplies = yes
		path = { 2101 2098 2102 2090 2003 }
	}
	
	# Supplies to New Britain
	convoy = { 
		id = { type = 28002 id = 30 } 
		transports = 10
		escorts = 0
		rubber = no 
		coal = no 
		steel = no 
		oil = no
		supplies = yes
		path = { 2101 2098 2102 2131 2027 2025 }
	} 
} 

