  country = { 
    tag = ETH
	alignment = { x = 30 y = 0 }

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 1295
	manpower = 240
	

    ownedprovinces =      {
	1290 1288 1294 1293 1296 1295 1297 
	 }
    controlledprovinces = {
	1290 1288 1294 1293 1296 1295 1297 
	  }
    nationalprovinces =   {
	1290 1288 1294 1293 1296 1295 1297 
	  }


	landunit = {
		#Regular army#

		id = { type = 14670 id = 1 } 
		location = 1290
		name = "Imperial Army"
		leader = 3305

		division = {
	        id = { type = 14670 id = 2 } 
			name = "Imperial Bodyguard"
			type = infantry
			strength  = 30
		}
		division = {
	        id = { type = 14670 id = 3 } 
			name = "1. Division"
			type = militia
			strength  = 70
		}
		division = {
	        id = { type = 14670 id = 4 } 
			name = "2. Division"
			type = militia
			strength  = 70
		}
	}

	landunit = {
		#Militia#

		id = { type = 14670 id = 5 } 
		location = 1293
		name = "1. Militia Corps"
		
		division = {
	        id = { type = 14670 id = 6 } 
			name = "1. Militia"
			type = militia
			strength  = 60
		}
		division = {
	        id = { type = 14670 id = 7 } 
			name = "2. Militia"
			type = militia
			strength  = 60
		}
	}

	landunit = {
		#Militia#
		id = { type = 14670 id = 8 } 
		location = 1288
		name = "2. Militia Corps"
		
		division = {
	        id = { type = 14670 id = 9 } 
			name = "3. Militia"
			type = militia
			strength  = 60
		}
		division = {
	        id = { type = 14670 id = 10 } 
			name = "4. Militia"
			type = militia
			strength  = 60
		}
	}



} 

