



country = { 
    tag = HUN
	alignment = { x = 10 y = -60 }

	manpower = 450
	capital = 633

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	techlevels = { 
		12000 13000 11000 14000 1000 1100 2000 5000 6000 9000 10000 8000
		8100 3000 3100 4000 4100 4200 4300
	 }
	 techapps = {
		12001 11001 11004 14001 14014 1001 6003 6004 3002 3005 4001 4101
		4102 4201 4202  4203  4204 3101 14005 1107
		4301 4302 4303
	}

    ownedprovinces      = { 729 629 731 759 728 730 739 618 631 632 727 726 622 634 633 630 627 626 741 738 }
    controlledprovinces = { 729 629 731 759 728 730 739 618 631 632 727 726 622 634 633 630 627 626 741 738 }
    nationalprovinces   = { 729 629 731 759 728 730 739 618 631 632 727 726 622 634 633 630 627 626 741 738 }


######################
###HUNGARIAN OOB###
######################

landunit = {
 id = { type = 28005 id = 1 }
 name = "1st Army"
 location = 633

  division = { 
   id = { type = 28005 id = 2 }
   name = "1st Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 3 }
   name = "2nd Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 4 }
   name = "3rd Corps"
   strength = 100
   type = infantry
                }

       }

########################
#########################

landunit = {
 id = { type = 28005 id = 5 }
 name = "2nd Army"
 location = 633

  division = { 
   id = { type = 28005 id = 6 }
   name = "4th Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 7 }
   name = "5th Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 8 }
   name = "6th Corps"
   strength = 100
   type = infantry
                }

       }

#############################
#############################

landunit = {
 id = { type = 28005 id = 9 }
 name = "3rd Army"
 location = 633

  division = { 
   id = { type = 28005 id = 10 }
   name = "7th Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 11 }
   name = "8th Corps"
   strength = 100
   type = infantry
                }

  division = { 
   id = { type = 28005 id = 12 }
   name = "9th Corps"
   strength = 100
   type = infantry
                }

       }

#################################
#################################

airunit = {
 id = { type = 28005 id = 13 }
 name = "1st Army Air Force"
 location = 630
 
  division = {
   id = { type = 28005 id = 14 }
   name = "1st Fighter Squadron"
   type = fighter
   model = 0
   strength = 30 
                }

  division = {
   id = { type = 28005 id = 15 }
   name = "1st Bomber Squadron"
   type = tactical_bomber
   model = 0
   strength = 30 
                }

      }

##################################
####################################
 


} 




