country = { 
    tag = IRE
	alignment = { x = -20 y = -10 }

	techlevels = { 
		12000 13000 11000 14000 1000 1100 2000 5000 6000 9000 10000 8000
		8100 3000 3100 4000 4100 4200 4300
	 }
	 techapps = {
		12001 11001 11004 14001 14014 1001 6003 6004 3002 3005 4001 4101
		4102 4201 4202  4203  4204 3101 14005 1107
		4301 4302 4303
	}

	manpower = 90

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200


	capital = 495
    ownedprovinces =      {
	492	 494 495 496  }
    controlledprovinces = {
	492 494 495 496
	  }
    nationalprovinces =   {
	492 494 495 496
	  }


	 landunit = {
	  id = { type = 18223 id = 1 }
	  name = "1st Thunderbolt Division"
	  location = 496
	  #leader = #Lt. Gen. Michael J. Costello#

	   division = {
		id = { type = 18223 id = 3 }
		name = "1st Thunderbolt Division"
		strength = 100
		type = infantry
				  }
	 }

	 landunit = {
	  id = { type = 18223 id = 2 }
	  name = "2nd Spearhead Division"
	  location = 495
	  #leader = #Maj. Gen. Hugo MacNeill#

	   division = {
		id = { type = 18223 id = 4 }
		name = "2nd Spearhead Division"
		strength = 100
		type = infantry
				  }
	 }
} 
