

country = { 
    tag = MAN
	alignment = { x = 0 y = -80 }
	puppet = JAP
	control = JAP
	
	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200
	manpower = 300

	capital = 	1559
	
    ownedprovinces =      {
		1557 1660 1661 1654 1667 1559 1655 
	 }
    controlledprovinces = {
		1557 1660 1661 1654 1667 1559 1655 
	  }
    nationalprovinces =   {
		1554 1555 1557 1660 1661 1654 1558 1667 1559 1623 1627 1556 1655 
	  }
#################################
###Manchukuo Army OOB35##########
#################################
landunit = {
		location = 1557
        id = { type = 11559 id = 1 } 
		name = "1st Fangtien Army"
		
		division = {
	        id = { type = 11559 id = 2 } 
			name = "1st Mixed Division"
			type = militia
			strength  = 90
				}
	} 
landunit = {
		location = 1559
        id = { type = 11559 id = 8 } 
		name = "2nd Jilin Army"
		
		division = {
	        id = { type = 11559 id = 9 } 
			name = "2nd Mixed Division"
			type = militia
			strength  = 60
				}
		division = {
	        id = { type = 11559 id = 13 } 
			name = "2nd Cavalry Division"
			type = cavalry
			strength  = 45
				}
	}
landunit = {
		location = 1660
        id = { type = 11559 id = 16 } 
		name = "3rd Qiqihar Army"
		
		division = {
	        id = { type = 11559 id = 17 } 
			name = "3rd Mixed division"
			type = militia
			strength  = 75
				}
				division = {
	        id = { type = 11559 id = 22 } 
			name = "5th Cavalry Brigade"
			type = cavalry
			strength  = 15
				}
	} 
landunit = {
		location = 1661
        id = { type = 11559 id = 23 } 
		name = "4th Harbin Army"
		
		division = {
	        id = { type = 11559 id = 24 } 
			name = "4th Mixed Division"
			type = militia
			strength  = 15
				}
		division = {
	        id = { type = 11559 id = 30 } 
			name = "41st Independent Brigade"
			type = militia
			strength  = 30
				}
		division = {
	        id = { type = 11559 id = 32 } 
			name = "6th Cavalry Brigade"
			type = cavalry
			strength  = 15
				}
	}
landunit = {
		location = 1655
        id = { type = 11559 id = 33 } 
		name = "5th Chengde Army"
		
		division = {
	        id = { type = 11559 id = 34 } 
			name = "5th Mixed Division"
			type = militia
			strength  = 45
				}
		division = {
	        id = { type = 11559 id = 37 } 
			name = "7th Cavalry Brigade"
			type = cavalry
			strength  = 15
				}
	}
####################################################
}
