  country = { 
    tag = MON
	alignment = { x = -80 y = 0 }
	puppet = SOV
	control = SOV

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200
	manpower = 20
	
	capital = 1532
	


    ownedprovinces =      {
	1546 1547 1532 1545 1550 1549 1536 

	 }
    controlledprovinces = {
	1546 1547 1532 1545 1550 1549 1536 

	  }
    nationalprovinces =   {
	1546 1547 1532 1545 1550 1549 1548 1551 1544 1542 1536 

	  }
	landunit = {
		location = 1549 #Choybalsan
		name = "Mongolian Army"			
        id = { type = 11532 id = 1 } 
	division = {
        id = { type = 11532 id = 2 } 
			name = "1st Division"	
			type = infantry
		}
	division = {
        id = { type = 11532 id = 3 } 
			name = "2nd Division"	
			type = cavalry
		}
	division = {
        id = { type = 11532 id = 4 } 
			name = "3rd Division"	
			type = militia
		}
	division = {
        id = { type = 11532 id = 5 } 
			name = "4th Division"	
			type = militia
		}
	}
} 