country = { 
    tag = NEP
	alignment = { x = 60 y = -20 }
	puppet = ENG
	control = ENG 
	
	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 	1494 
	manpower = 20

    ownedprovinces =      {
1494 
	 }
    controlledprovinces = {
1494 
	  }
    nationalprovinces =   {
1494 
	  }
	landunit = {
		location = 1494
		name = "Nepal Army"			
        id = { type = 11494 id = 1 } 
	division = {
        id = { type = 11494 id = 2 } 
			name = "Regulars"	
			type = infantry
		}
	division = {
        id = { type = 11494 id = 3 } 
			name = "Militia"	
			type = militia
		}
	}
} 
