

country = { 
    tag = ROM
	alignment = { x = 20 y = -50 }

	capital = 757

	techlevels = { 
		12000 13000 11000 14000 1000 1100 2000 5000 6000 9000 10000 8000
		8100 3000 3100 4000 4100 4200 4300
	 }
	 techapps = {
		12001 11001 11004 14001 14014 1001 6003 6004 3002 3005 4001 4101
		4102 4201 4202  4203  4204 3101 14005 1107
		4301 4302 4303
	}

	manpower = 450
	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

    ownedprovinces      = { 757 736 760 768 767 763 }
    controlledprovinces = { 757 736 760 768 767 763 }
    nationalprovinces   = { 757 736 760 768 767 763 }

	landunit = {
		location = 739	#Timisoara
		name = "Corp 7 Armata"			
        id = { type = 32000 id = 1 } 
	division = {
        id = { type = 32000 id = 2 } 
			name = "Divizia 1 Infanterie"	#Timisoara
			type = infantry
			strength = 70
			extra = engineer
		}
	division = {
        id = { type = 32000 id = 3 } 
			name = "Divizia 18 Infanterie"	#Sibiu
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 4 } 
			name = "Divizia 19 Infanterie"	
			type = infantry
			strength = 70
		}
	}
	landunit = {
		location = 736	#Craiova
		name = "Corp 1 Armata" 
        id = { type = 32000 id = 5 } 
	division = {
        id = { type = 32000 id = 6 } 
			name = "Divizia 2 Infanterie"
			type = infantry
			strength = 70
			extra = artillery
		}
	division = {
        id = { type = 32000 id = 7 } 
			name = "Divizia 3 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 8 } 
			name = "Divizia 4 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 9 } 
			name = "Divizia 11 Infanterie"
			type = infantry
			strength = 70
		}
	}

	landunit = {
		location = 759	#Brasov
		name = "Corp 5 Armata" 
        id = { type = 32000 id = 10 } 
	division = {
        id = { type = 32000 id = 11 } 
			name = "Divizia 5 Infanterie"
			type = infantry
			strength = 70
					}
	division = {
        id = { type = 32000 id = 12 } 
			name = "Divizia 6 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 13 } 
			name = "Divizia 13 Infanterie"
			type = infantry
			strength = 70
		}
	}
	landunit = {
		location = 757	#Bucuresti
		name = "Corp 4 Armata" 
        id = { type = 32000 id = 14 } 
	division = {
        id = { type = 32000 id = 15 } 
			name = "Divizia 7 Infanterie"
			type = infantry
			strength = 70
			extra = antiair
		}
	division = {
        id = { type = 32000 id = 16 } 
			name = "Divizia 8 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 17 } 
			name = "Divizia 14 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 47 } 
			name = "Divizia 1 Blindate"
			type = panzer
			model = 0
			strength = 60
		}
	}
	landunit = {
		location = 868	#Constanta
		name = "Corp 2 Armata" 
        id = { type = 32000 id = 18 } 
	division = {
        id = { type = 32000 id = 19 } 
			name = "Divizia 9 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 20 } 
			name = "Divizia 10 Infanterie"
			type = infantry
			strength = 70
		}
	}
	landunit = {
		location = 763	#Chisinau
		name = "Corp 3 Armata" 
        id = { type = 32000 id = 21 } 
	division = {
        id = { type = 32000 id = 22 } 
			name = "Divizia 12 Infanterie"
			type = infantry
			strength = 70
			extra = artillery
		}
	division = {
        id = { type = 32000 id = 23 } 
			name = "Divizia 15 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 24 } 
			name = "Divizia 21 Infanterie"
			type = infantry
			strength = 70
			extra = antitank
		}
	}
	landunit = {
		location = 729	#Oradea
		name = "Corp 6 Armata" 
        id = { type = 32000 id = 25 } 
	division = {
        id = { type = 32000 id = 26 } 
			name = "Divizia 16 Infanterie"
			type = infantry
			strength = 70
					}
	division = {
        id = { type = 32000 id = 27 } 
			name = "Divizia 17 Infanterie"
			type = infantry
			strength = 70
		}
	division = {
        id = { type = 32000 id = 28 } 
			name = "Divizia 20 Infanterie"
			type = infantry
			strength = 70
		}
	}
	landunit = {
		location = 728	#Piatra Neamt
		name = "Corp Munte" 
        id = { type = 32000 id = 29 } 
	division = {
        id = { type = 32000 id = 30 } 
			name = "Brigada 1 Mixta Munte"
			type = bergsjaeger
			strength = 100
			extra = artillery
					}
	division = {
        id = { type = 32000 id = 31 } 
			name = "Brigada 2 Mixta Munte"
			type = bergsjaeger
			strength = 100
			extra = engineer
		}
	division = {
        id = { type = 32000 id = 32 } 
			name = "Brigada 3 Mixta Munte"
			type = bergsjaeger
			strength = 100
		}
	}

	landunit = {
		location = 760	#Ploiesti
		name = "Corp Cavalerie" 
        id = { type = 32000 id = 33 } 
	division = {
        id = { type = 32000 id = 34 } 
			name = "Divizia 1 Cavalerie"
			type = cavalry
			strength = 40
			extra = artillery
		}
	division = {
        id = { type = 32000 id = 35 } 
			name = "Divizia 5 Cavalerie"
			type = cavalry
			strength = 30
		}
	division = {
        id = { type = 32000 id = 36 } 
			name = "Divizia 6 Cavalerie"
			type = cavalry
			strength = 30
		}
	division = {
        id = { type = 32000 id = 37 } 
			name = "Divizia 7 Cavalerie"
			type = cavalry
			strength = 30
		}
	division = {
        id = { type = 32000 id = 38 } 
			name = "Divizia 8 Cavalerie"
			type = cavalry
			strength = 30
		}
	division = {
        id = { type = 32000 id = 39 } 
			name = "Divizia 9 Cavalerie"
			type = cavalry
			strength = 30
		}
	}
	navalunit = {
		location = 868
		name = "Divizia de Mare"
		leader = 4369
        id = { type = 32000 id = 40 } 
	division = {      
	id = { type = 32000 id = 41 } 	
			name = "Destroyer Squadron"	
			type = destroyer
			model = 0
		}
	}
	airunit = {
		location = 757 #bucuresti
		name = "Gruparea Aeriana de Lupta"
		leader = 4372
	id = { type = 32000 id = 42 }
	division = {
	id = { type = 32000 id = 43 }	
			name = "Flotila Vanatoare"
			type = fighter
			model = 0
			strength = 50
		}
	division = {
	id = { type = 32000 id = 44 }	
			name = "Flotila Bombardament"
			type = tactical_bomber
			model = 0
			strength = 10
		}
	division = {
	id = { type = 32000 id = 45 }	
			name = "Flotila Hidroavioane"
			type = naval_bomber
			model = 0
			strength = 28
		}
	division = {
	id = { type = 32000 id = 46 }	
			name = "Flotila Transport"
			type = transport_plane
			model = 0
			strength = 11
		}
	}
#if adding more units, note that id 47 has been used.
} 
