country = { 
    tag = SAU
	alignment = { x = 0 y = -10 }

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 1277

	manpower = 80

    ownedprovinces =      {
	1282 1347 1277 1349 1279 1276 

	 }
    controlledprovinces = {
	1282 1347 1277 1349 1279 1276 

	  }
    nationalprovinces =   {
	1282 1347 1277 1349 1279 1276 

	  }


	landunit = {
		location = 1277
		name = "Saudi Army"			
        id = { type = 11277 id = 1 } 
	division = {
        id = { type = 11277 id = 2 } 
			name = "Regulars"	
			type = infantry
			strength = 50
		}
	division = {
        id = { type = 11277 id = 3 } 
			name = "Levies"	
			type = militia
		}
	}
} 
