country = { 
    tag = SIK
	alignment = { x = 0 y = 0 }

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 	1514 
	manpower = 200
	
    ownedprovinces =      {
1432 1433 1507 1509 1510 1513 1514 1541 1609 1705 1708 1701 1700 1702 1704 1703 1712 1709 1724
	 }
    controlledprovinces = {
1432 1433 1507 1509 1510 1513 1514 1541 1609 1705 1708 1701 1700 1702 1704 1703 1712 1709 1724
	  }
    nationalprovinces =   {
1432 1433 1507 1509 1510 1513 1514 1541 
	  }


	landunit = {
		location = 1514
		name = "Sinkiang Warlord Army"			
        id = { type = 11514 id = 1 } 
	division = {
        id = { type = 11514 id = 2 } 
			name = "1st Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 3 } 
			name = "2nd Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 4 } 
			name = "3rd Division"	
			type = militia
		}
	}
	landunit = {
		location = 1609 #Nanning
		name = "Kwangsi Warlord Army"			
        id = { type = 11514 id = 5 } 
	division = {
        id = { type = 11514 id = 6 } 
			name = "1st Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 7 } 
			name = "2nd Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 16 } 
			name = "3rd Division"	
			type = militia
		}
	}
	landunit = {
		location = 1704 #Guangzhou
		name = "Kwantung Warlord Army"			
        id = { type = 11514 id = 8 } 
	division = {
        id = { type = 11514 id = 9 } 
			name = "1st Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 10 } 
			name = "2nd Division"	
			type = militia
		}
	division = {
        id = { type = 11514 id = 15 } 
			name = "3rd Division"	
			type = militia
		}
	}
	airunit = {
		location = 1704 #Guangzhou
		name = "Kwantung Airforce"			
        id = { type = 11514 id = 11 } 
	division = {
        id = { type = 11514 id = 12 } 
			name = "Fighter Squadron"	
			type = fighter
			model = 0
			strength = 30
		}
	}
	airunit = {
		location = 1609 #Nanning
		name = "Kwangsi Airforce"			
        id = { type = 11514 id = 13 } 
	division = {
        id = { type = 11514 id = 14 } 
			name = "Fighter Squadron"	
			type = fighter
			model = 0
			strength = 20
		}
	}
}

