country = { 
    tag = TIB
	alignment = { x = 20 y = 0 }

	# Resource Reserves
	oil		= 200
	steel	= 200
	coal	= 200
	rubber	= 200

	capital = 	1503

	manpower = 30
    ownedprovinces =      {
1502 1503 1511 1512 1506 1579 1440 1576 1508 1505 1575 1577 
	 }
    controlledprovinces = {
1502 1503 1511 1512 1506 1579 1440 1576 1508 1505 1575 1577 
	  }
    nationalprovinces =   {
1502 1503 1511 1512 1506 1579 1440 1576 1508 1505 1575 1577 
	  }


	landunit = {
		location = 1503
		name = "Tibetan Army"			
        id = { type = 11503 id = 1 } 
	division = {
        id = { type = 11503 id = 2 } 
			name = "1st Division"	
			type = militia
		}
	division = {
        id = { type = 11503 id = 3 } 
			name = "2nd Division"	
			type = militia
		}
	division = {
        id = { type = 11503 id = 4 } 
			name = "3rd Division"	
			type = militia
		}
	}
}