#
#
# Province Setup
#
#


#victory points..
###############################################
# Germany
###############################################


 
province = { id = 602 points = 30 } #Berlin 
province = { id = 588 points = 5 } #Hamburg
province = { id = 586 points = 5 } #Kiel
province = { id = 579 points = 5 } #Erfurt
province = { id = 559 points = 25 } #Essen
province = { id = 574 points = 5 } #Nürnberg
province = { id = 575 points = 5 } #Mannheim
province = { id = 604 points = 5 } #Dresden
province = { id = 558 points = 10 } #Köln
province = { id = 605 points = 5 } #Leipzig
province = { id = 575 points = 5 }#Stuttgart 
province = { id = 562 points = 10 } #München


###############################################
# UK
###############################################

#london#
province = {	id = 499	points = 30	}#London
province = {	id = 1459	points = 5	}#Bombay
province = {	id = 1490	points = 5	}#Calcutta
province = {	id = 1446	points = 5	}#Delhi
province = {	id = 1099	points = 5	}#Alexandria
province = {	id = 1100	points = 5	}#Port Said
province = {	id = 1102	points = 5	}#Suez
province = {	id = 989	points = 7	}#Gibraltar
province = {	id = 896	points = 3	}#Malta
province = {	id = 488	points = 10	}#Newcastle
province = {	id = 487	points = 5	}#Edinburgh
province = {	id = 486	points = 5	}#Glasgow
province = {	id = 497	points = 5	}#Birgmingham
province = {	id = 493	points = 5	}#Belfast
province = {	id = 1766	points = 3	}#Singapore
province = {	id = 1717	points = 2	}#Hongkong


###############################################
# France
###############################################
#paris#
province = {	id = 527	points = 20	}#Paris
province = {	id = 915	points = 5	}#Vichy
province = {	id = 555	points = 2	}#Strassbourg
province = {	id = 542	points = 7	}#Colmar
province = {	id = 929	points = 7	}#Marseilles
province = {	id = 948	points = 7	}#Bordeaux
province = {	id = 944	points = 7	}#Toulouse
province = {	id = 531	points = 2	}#Caen
province = {	id = 1077	points = 5	}#Alger
province = {	id = 1081	points = 5	}#Tunis
province = {	id = 1033	points = 5	}#Dakar
province = {	id = 1274	points = 5	}#Damascus
province = {	id = 1733	points = 25	}#Saigon


###############################################
# Italy
###############################################
province = {	id = 908	points = 15	}#Roma
province = {	id = 912	points = 7	}#Milano
province = {	id = 567	points = 7	}#Venezia
province = {	id = 933	points = 7	}#Genoa
province = {	id = 901	points = 6 }#Napoli
province = {	id = 897	points = 5 }#Messina
province = {	id = 905	points = 5 }#Bologna
province = {	id = 1085	points = 3 }#Tripoli
province = {	id = 893	points = 5 }#Tarento

###############################################
# Soviet
###############################################
province = {	id = 846	points = 50	}#Moscow
province = {	id = 788	points = 30	}#Leningrad
province = {	id = 1225	points = 30	}#Stalingrad
province = {	id = 1359	points = 15	}#Baku
province = {	id = 1663	points = 10	}#Vladivostok
province = {	id = 1535	points = 5	}#Irkutsk
province = {	id = 822	points = 5	}#Murmansk
province = {	id = 839	points = 5	}#Archangelsk
province = {	id = 1222	points = 2	}#Maikop
province = {	id = 861	points = 2	}#Rostov
province = {	id = 862	points = 2	}#Sevestapol
province = {	id = 764	points = 2	}#Odessa
province = {	id = 857	points = 2	}#Kharkov
province = {	id = 775	points = 5	}#Kiev
province = {	id = 1371	points = 5	}#Magnitogorsk
province = {	id = 778	points = 5	}# Minsk
province = {	id = 781	points = 5	}#Smolensk
province = {	id = 843	points = 2	}#Vologda
province = {	id = 1373	points = 2	}#Kujbysjev
province = {	id = 784	points = 2	}#Vitebsk
province = {	id = 845	points = 2	}#Kalinin
province = {	id = 852	points = 2	}#Kaluga


###############################################
# USA
###############################################

province = {	id = 0	points = 20	}#
province = {	id = 0	points = 20 }#
province = {	id = 22		points = 1	}#Honolulu
province = {	id = 178	points = 1	}#Washington
province = {	id = 106	points = 1	}#Seattle
province = {	id = 97		points = 1	}#Portland
province = {	id = 5		points = 1	}#Spokane
province = {	id = 6		points = 1	}#Bures
province = {	id = 158	points = 1	}#San Fransisco
province = {	id = 155	points = 1	}#Sacramento
province = {	id = 92		points = 1	}#Los Angeles
province = {	id = 156	points = 1	}#San Bernadino
province = {	id = 89		points = 1	}#Phoenix
province = {	id = 87		points = 1	}#Albuquerque
province = {	id = 86		points = 1	}#Denver
province = {	id = 90		points = 1	}#Cheyenne
province = {	id = 91		points = 1	}#Salt Lake City
province = {	id = 104	points = 1	}#Idaho falls
province = {	id = 105	points = 1	}#Great Falls
province = {	id = 113	points = 1	}#Bismarck
province = {	id = 114	points = 1	}#Rapid City
province = {	id = 191	points = 1	}#Omaha
province = {	id = 195	points = 1	}#Kansas City
province = {	id = 196	points = 1	}#Tulsa
province = {	id = 8		points = 1	}#Dallas
province = {	id = 9		points = 1	}#San Antonio
province = {	id = 203	points = 1	}#Houston
province = {	id = 204	points = 1	}#New Orleans
province = {	id = 209	points = 1	}#Shreveport
province = {	id = 208	points = 1	}#Little Rock
province = {	id = 194	points = 1	}#Springfield
province = {	id = 193	points = 1	}#St.Louis
province = {	id = 192	points = 1	}#Des Moines
province = {	id = 112	points = 1	}#Minneapolis
province = {	id = 117	points = 1	}#Milwaukee
province = {	id = 187	points = 1	}#Chicago
province = {	id = 188	points = 1	}#Indianapolis
province = {	id = 116	points = 1	}#Detroit
province = {	id = 121	points = 1	}#Cleveland
province = {	id = 189	points = 1	}#Louisville
province = {	id = 184	points = 1	}#Nashville
province = {	id = 210	points = 1	}#Jackson
province = {	id = 211	points = 1	}#Mobile
province = {	id = 212	points = 1	}#Miami
province = {	id = 217	points = 1	}#Atlanta
province = {	id = 216	points = 1	}#Columbia
province = {	id = 183	points = 1	}#Charlotte
province = {	id = 182	points = 1	}#Charleston
province = {	id = 181	points = 1	}#Norfolk
province = {	id = 177	points = 1	}#Philadelphia
province = {	id = 122	points = 1	}#Pittsburgh
province = {	id = 124	points = 1	}#New York
province = {	id = 129	points = 1	}#Buffalo
province = {	id = 125	points = 1	}#Boston
province = {	id = 150	points = 1	}#Concord

###############################################
# Canada
###############################################

province = {	id = 149	points = 1	}#Montreal
province = {	id = 128	points = 1	}#Ottowa
province = {	id = 4	points = 1	}#Vancouver

###############################################
# Japan
###############################################

province = {	id = 1822	points = 10	}#Tokyo
province = {	id = 1823	points = 10	}#Nagoya
province = {	id = 1825	points = 10	}#Osaka
province = {	id = 1682	points = 10	}#Hiroshima
province = {	id = 1832	points = 1	}#Toyohare
province = {	id = 1833	points = 1	}#Asahikawa
province = {	id = 1834	points = 2	}#Sapporo
province = {	id = 1818	points = 5	}#Akita
province = {	id = 1819	points = 5	}#Sendai
province = {	id = 1820	points = 5	}#Fukushima
province = {	id = 1821	points = 5	}#Niigata
province = {	id = 1824	points = 5	}#Kanazawa
province = {	id = 1683	points = 5	}#Kochi
province = {	id = 1684	points = 5	}#Fukuoka
province = {	id = 1681	points = 5	}#Kagashima
province = {	id = 1674	points = 5	}#Keijo
province = {	id = 1716	points = 10	}#Taihoku
province = {	id = 2035	points = 5	}#Truk


###############################################
# Nationalist China
###############################################
province = {	id = 1698	points = 3	}#
province = {	id = 1695	points = 1	}#
province = {	id = 1700	points = 1	}# 
province = {	id = 1701	points = 1	}#
province = {	id = 1724	points = 1	}#
province = {	id = 1609	points = 1	}#
province = {	id = 1606	points = 1	}#
province = {	id = 1611	points = 1	}#
province = {	id = 1614	points = 1	}#
province = {	id = 1615	points = 1	}#
province = {	id = 1616	points = 1	}# 
province = {	id = 1617	points = 1	}#
province = {	id = 1613	points = 1	}#
province = {	id = 1610	points = 1	}#
province = {	id = 1573	points = 1	}#
province = {	id = 1570	points = 1	}#
province = {	id = 1574	points = 1	}#
province = {	id = 1691	points = 1	}#


###############################################
# Central Europe
###############################################

#Czechoslovakia
province = { 	id = 615	points = 6 }#
province = { 	id = 618	points = 4 }#
province = { 	id = 612	points = 2 }#

#Sschweiz
province = {	id = 541	points = 1 }#
province = {	id = 936	points = 1 }#

#Austria
province = {	id = 621	points = 6 }#
province = {	id = 573	points = 2 }#
province = {	id = 610	points = 2 }#
province = {	id = 623	points = 2 }#

#Poland
province = {	id = 643	points = 4 }#
province = {	id = 645	points = 2 }#
province = {	id = 637	points = 2 }#
province = {	id = 638	points = 2 }#
province = {	id = 723	points = 2 }#
province = {	id = 725	points = 2 }#


#Romania
province = {	id = 760	points = 4 }#
province = {	id = 757	points = 2 }#
province = {	id = 761	points = 2 }#

#Albania
province = {	id = 754	points = 2 }#Tirane

#Yugoslavia
province = {	id = 738	points = 2 }#
province = {	id = 625	points = 2 }#
province = {	id = 745	points = 2 }#

#Hungary
province = {	id = 633	points = 2 }#Budapest
province = {	id = 626	points = 2 }#Pecs
province = {	id = 630	points = 1 }#Debrecen

#Bulgaria
province = {	id = 750	points = 1 }#Sofia
province = {	id = 871	points = 1 }#Plovdiv
province = {	id = 809	points = 1 }#Varna

#Greece
province = {	id = 891	points = 1 }#Athinai
province = {	id = 887	points = 1 }#Iraklion
province = {	id = 872	points = 1 }#Thessaloniki

################################
# Scandinavia
################################

#Sweden
province = {	id = 2160	points = 4 }#Stockholm
province = {	id = 660	points = 2 }#Göteborg
province = {	id = 653	points = 1 }#Malmö
province = {	id = 681	points = 1 }#Gällivare
province = {	id = 691	points = 1 }#Örebro
province = {	id = 695	points = 1 }#Falun


#Denmark#
province = {	id = 594	points = 1	}#Kopenhavn
province = {	id = 655	points = 1	}#Aarhus
province = {	id = 596	points = 1 }#Odense

#Norway#
province = { 	id = 664	points = 3 }#Oslo
province = { 	id = 671	points = 1 }#Bergen
province = { 	id = 674	points = 1 }#Trondheim
province = { 	id = 662	points = 1 }#Stavanger
province = { 	id = 663	points = 1 }#Kristiansand
province = { 	id = 680	points = 1 }#Narvik


#Finland
province = { 	id = 706	points = 3 }#Helsinki
province = { 	id = 787	points = 1 }#Vipuri
province = { 	id = 705	points = 1 }#Turku
province = { 	id = 798	points = 1 }#Vaasa

#Estonia
province = { 	id = 707	points = 2 }#Tallinn

#Latvia
province = { 	id = 709	points = 2 }#Riga

#Lithuania
province = { 	id = 715	points = 2 }#Kaunas

###############################################
# Western Europe
###############################################

#Netherlands
province = {	id = 550	points = 5	}#Amsterdam
province = {	id = 1773	points = 2	}#
province = {	id = 1950	points = 2	}#
province = {	id = 1780	points = 3	}#Batavia
province = {	id = 1774	points = 2	}#
province = {	id = 1760	points = 2	}#
province = {	id = 1968	points = 2	}#
province = {	id = 1787	points = 2	}#

#Belgium
province = {	id = 552	points = 4	}#Bruxelles
province = {	id = 548	points = 2	}#Antwerpen
province = {	id = 1135	points = 1	}#Banana
province = {	id = 1130	points = 1	}#Leopoldville
province = {	id = 1187	points = 1	}#Elisabethville

#Spain
province = {	id = 972	points = 3 }#Madrid
province = {	id = 1009	points = 1 }#Ceuta
province = {	id = 981	points = 2	}#Valencia
province = {	id = 909	points = 2	}#Barcelona
province = {	id = 990	points = 1	}#Malaga
province = {	id = 966	points = 1	}#Vallalido
province = {	id = 957	points = 1	}#Burgos
province = {	id = 988	points = 1	}#Sevilla

#Portugal
province = {	id = 975	points = 3 }#Lissabon
province = {	id = 964	points = 1	}#Porto
province = {	id = 1136	points = 1 }#Luanda
province = {	id = 1722	points = 1 }#Macao
province = {	id = 2007	points = 1	}#Dili
province = {	id = 1176	points = 1	}#Lourenzo Marques
province = {	id = 456	points = 1	}#Cap Verde
province = {	id = 451	points = 1	}#Azores

#Luxemburg
province = {	id = 553	points = 1 }#Luxemburg

#Ireland
province = {	id = 495	points = 2 }#Dublin

###############################################
# Middle East
###############################################

#Turkey
province = {	id = 873	points = 3 }#Istanbul
province = {	id = 878	points = 1 }#Izmir
province = {	id = 879	points = 1 }#Izmit
province = {	id = 1262	points = 1 }
province = {	id = 1261	points = 1 }
province = {	id = 1210	points = 1 }
province = {	id = 1213	points = 2 }#Ankara


#Persia
province = {	id = 1364	points = 2 }#Teheran
province = {	id = 1356	points = 1 }#Abadan
province = {	id = 1350	points = 1 }#Shiraz
province = {	id = 1357	points = 1 }#Esfahan
province = {	id = 1414	points = 1 }#Bandar Abbas
province = {	id = 1358	points = 1 }#Tabriz

#Iraq
province = {	id = 1272	points = 3 }#Bagdad
province = {	id = 1271	points = 2 }#Mosul
province = {	id = 1355	points = 1 }#Basra


###############################################
# Arabia
###############################################

#Oman
province = {	id = 1346	points = 2 }#Muscat

#Yemen
province = {	id = 1283	points = 2 }#Aden

#Saudi Arabia
province = {	id = 1277	points = 1 }#Riyadh


###############################################
# Africa
###############################################
#Ethiopia
province = {	id = 1295	points = 2 }#Addis Abeba

#Liberia
province = {	id = 1040	points = 1 }#Monorovia

#South africa
province = {	id = 1156	points = 3 }#Capetown
province = {	id = 1175	points = 3 }#Johannesburg
province = {	id = 1167	points = 2 }#Port Elizabeth
province = {	id = 1172	points = 2 }#Durban


###############################################
# Far East
###############################################

#Afghanistan
province = {	id = 1437	points = 1 }#Kabul
province = {	id = 1408	points = 1 }#Herat

#Tibet
province = {	id = 1503	points = 2 }#Lhasa

#Sinkiang
province = {	id = 1704	points = 2 }
province = {	id = 1514	points = 2 }

#Communist China
province = {	id = 1571	points = 1 }#
province = {	id = 1570	points = 1 }#

#Mongolia
province = {	id = 1532	points = 1 }#Ulan Bator



#Manchuko
province = {	id = 1559	points = 2 }#
province = {	id = 1661	points = 4 }#Harbin
province = {	id = 1667	points = 2 }#


#Siam
province = {	id = 1744	points = 2 }#Bangkok

#Philipinnes
province = {	id = 1804	points = 2 }#Manilla
province = {	id = 1803	points = 1 }#
province = {	id = 1802	points = 1 }#
province = {	id = 1800	points = 1 }#
province = {	id = 1799	points = 1 }#
province = {	id = 1974	points = 1 }#
province = {	id = 1975	points = 1 }#
province = {	id = 1976	points = 1 }#


#Australia
province = {	id = 2076	points = 2 }#Canberra
province = {	id = 2025	points = 2 }#Rabaul
province = {	id = 2003	points = 2 }#
province = {	id = 2101	points = 1 }#
province = {	id = 2042	points = 1 }#Perth
province = {	id = 2105	points = 1 }#
province = {	id = 2075	points = 1 }#
province = {	id = 2078	points = 1 }#

#New Zealand
province = {	id = 2140	points = 1 }#Wellington
province = {	id = 2135	points = 1 }#Auckland


#Burma
province = {	id = 1590	points = 2 }#Rangoon

#The Aleutians
province = {	id = 2	points = 1 }#Atka
province = {	id = 1880	points = 1 }#Amchitka
province = {	id = 1883	points = 1 }#Kiska
province = {	id = 1863	points = 1 }#Attu





###############################################
# Americas
###############################################
#Uruguay
province = {	id = 368	points = 1 }#

#Paraguay
province = {	id = 366	points = 1 }#

#Argentine
province = {	id = 384	points = 6 }#
province = {	id = 385	points = 2 }#
province = {	id = 370	points = 2 }#

#Chile
province = {	id = 372	points = 4 }#
province = {	id = 342	points = 2 }#
province = {	id = 338	points = 2 }#

#Brazil
province = {	id = 356	points = 2 }#
province = {	id = 351	points = 4 }#
province = {	id = 318	points = 2 }#
province = {	id = 354	points = 2 }#
province = {	id = 322	points = 2 }#

#Bolivia
province = {	id = 343	points = 2 }#

#Ecuador
province = {	id = 292	points = 2 }#

#Venzuela
province = {	id = 277	points = 2 }#

#Colombia
province = {	id = 284	points = 2 }#

#Panama
province = {	id = 287	points = 1 }#Panama City
province = {	id = 288	points = 5 }#Colon (Channel Zone)

#Costa Rica
province = {	id = 286	points = 1 }#

#Nicaragua
province = {	id = 255	points = 1 }#

#Honduras
province = {	id = 254	points = 1 }#

#El Salvador
province = {	id = 253	points = 1 }#

#Guatemala
province = {	id = 252	points = 1 }#

#Port au Prince
province = {	id = 261	points = 1 }#

#Santo Domingo
province = {	id = 262	points = 1 }#

#Cuba
province = {	id = 229	points = 2 }#

#Mexico
province = {	id = 244	points = 2 }#Ciudad de Mexico
province = {	id = 238	points = 1 }#Veracruz
province = {	id = 200	points = 1 }#Culican
province = {	id = 237	points = 1 }#Monterrey
province = {	id = 248	points = 1 }#Acapulco












